# Generated by Django 4.2 on 2023-04-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timing',
        ),
    ]
